spring:
    jpa:
        database: MYSQL     

    datasource:
        url: jdbc:mysql://172.18.0.2:3306/mydb
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver